"""Add cv_email field to user_profiles

Revision ID: 2347e1d3fbd6
Revises: 052495d15c36
Create Date: 2025-11-25 17:52:13.701530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2347e1d3fbd6'
down_revision: Union[str, Sequence[str], None] = '052495d15c36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('cv_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'cv_email')
    # ### end Alembic commands ###
