"""Add draft status and hobbies to user profile

Revision ID: 246291cbef07
Revises: ef4360335a1b
Create Date: 2025-11-11 10:43:55.846058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '246291cbef07'
down_revision: Union[str, Sequence[str], None] = 'ef4360335a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('is_draft', sa.Boolean(), nullable=True))
    op.add_column('user_profiles', sa.Column('is_validated', sa.Boolean(), nullable=True))
    op.add_column('user_profiles', sa.Column('hobbies', sa.JSON(), nullable=True))
    op.add_column('user_profiles', sa.Column('additional_info', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'additional_info')
    op.drop_column('user_profiles', 'hobbies')
    op.drop_column('user_profiles', 'is_validated')
    op.drop_column('user_profiles', 'is_draft')
    # ### end Alembic commands ###
